name: b1_first_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  english_words: ^4.0.0
  provider: ^6.1.5
  http: ^1.5.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  universal_io: ^2.2.2
  flutter_riverpod: ^2.5.1
  video_player: ^2.10.0
  just_audio: ^0.10.5
  file_picker: ^10.3.2
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.1
  flutter_dotenv: ^6.0.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^10.0.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/audio/
    - .env
